version: '3'
volumes:
  persistent:

services:
  bot:
    build: .
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ${RECORDINGS_PATH:?Path on the disk where to store ready recordings}:/recordings:rw
      - persistent:/persistent:rw