version: '3'
volumes:
  persistent:

services:
  bot:
    build: .
    restart: always
    ports:
      # uncomment for debugging
      # - 9000:9000                 # node.js
      # - ${NOVNC_PORT:-9001}:9001  # novnc
    environment:
      - NOVNC_PORT=${NOVNC_PORT:-}
    volumes:
      - ${RECORDINGS_PATH:?Path on the disk where to store ready recordings}:/recordings:rw
      - persistent:/persistent:rw